# pyup.io config file
# see https://pyup.io/docs/configuration/ for all available options

schedule: every month

requirements:
  - requirements.txt:
      pin: False
      update: False
  - requirements_test.txt:
      pin: False
      update: False
  - requirements_rtfd.txt:
      pin: False
      update: False
  - requirements_dev.txt:
      pin: True
      update: all
  - requirements_dev_npy.txt:
      pin: True
      update: all
  - requirements_dev_optional.txt:
      pin: True
      update: all
