version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" != "tag" ];
        then
          towncrier build --version Unreleased --yes;
        fi

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

formats: all

python:
   install:
   - method: pip
     path: .
     extra_requirements:
        - docs
