version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  commands:
    - pip install hatch
    - hatch run docs:rtd

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

formats: all
