version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" != "tag" ];
        then
          towncrier build --version Unreleased --yes;
        fi
    build:
        html:
          - mkdocs build --strict --site-dir $READTHEDOCS_OUTPUT/html
mkdocs:
  configuration: mkdocs.yml

python:
   install:
   - method: pip
     path: .
     extra_requirements:
        - docs
        - remote
