name: Check changelog entries

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-changelogs:
    name: Check changelog entries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@6ee6290f1cbc4156c0bdd66691b2c144ef8df19a # v7.4.0

      - name: Check changelog entries
        run: uv run --no-sync python ci/check_changelog_entries.py
