name: CodSpeed Benchmarks

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9am UTC
  pull_request:
    types: [labeled]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: codspeed-macro
    if: |
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'benchmark'))
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Install Hatch
      uses: pypa/hatch@f647ed70d49adb885f53a27d1c7f5bdaeacf2c60
      with:
        version: '1.16.5'
    - name: Run the benchmarks
      uses: CodSpeedHQ/action@4296e51e7041e24dadb86d1d6e8b9320d223dbe8 # v5.0.3
      env:
        ZARR_BENCHMARK_CLEAR_CACHE: '1'
      with:
          mode: walltime
          run: hatch run test.py3.12-minimal:pytest tests/benchmarks --codspeed
