name: CodSpeed Benchmarks

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9am UTC
  pull_request:
    types: [labeled]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: codspeed-macro
    if: |
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'benchmark'))
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Install Hatch
      uses: pypa/hatch@257e27e51a6a5616ed08a39a408a21c35c9931bc
      with:
        version: '1.16.5'
    - name: Run the benchmarks
      uses: CodSpeedHQ/action@658a901452bb54c799643e060733b7afe9121b8d # v4.14.0
      with:
          mode: walltime
          run: hatch run test.py3.12-minimal:pytest tests/benchmarks --codspeed
