# Attributed to NumPy https://github.com/numpy/numpy/pull/25894
# https://github.com/numpy/numpy/blob/d2d2c25fa81b47810f5cbd85ea6485eb3a3ffec3/.github/workflows/emscripten.yml

name: Pyodide wheel

on:
  # TODO: refine after this is ready to merge
  [push, pull_request, workflow_dispatch]

env:
  FORCE_COLOR: 3
  PYODIDE_VERSION: "https://github.com/pyodide/pyodide-build-environment-nightly/releases/download/20250523-emscripten_4.0.9/xbuildenv.tar.bz2"
  # PYTHON_VERSION and EMSCRIPTEN_VERSION are determined by PYODIDE_VERSION.
  # The appropriate versions can be found in the Pyodide repodata.json
  # "info" field, or in Makefile.envs:
  # https://github.com/pyodide/pyodide/blob/main/Makefile.envs#L2
  PYTHON_VERSION: 3.13 # any 3.13.x version works
  EMSCRIPTEN_VERSION: 4.0.9
  NODE_VERSION: 22

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read  # to fetch code (actions/checkout)

jobs:
  build_wasm_emscripten:
    name: Build and test Zarr for Pyodide
    runs-on: ubuntu-latest
    # To enable this workflow on a fork, comment out:
    # FIXME: uncomment after this is ready to merge
    # if: github.repository == 'zarr-developers/zarr-python'
    steps:
      - name: Checkout Zarr repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}
          actions-cache-folder: emsdk-cache

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pyodide-build
        run: python -m pip install pyodide-build

      - name: Build Zarr for Pyodide
        run: |
          pyodide xbuildenv install --url ${{ env.PYODIDE_VERSION }}
          pyodide build

      - name: Run Zarr tests for Pyodide
        run: |
          # Avoid missing asyncio plugin error from pytest, unavailable in Pyodide
          if grep -q 'asyncio_mode = "auto"' "pyproject.toml"; then sed '/asyncio_mode = "auto"/d' "pyproject.toml" > temp && mv temp "pyproject.toml"; fi
          pyodide venv .venv-pyodide
          source .venv-pyodide/bin/activate
          python -m pip install dist/*.whl
          python -m pip install pytest pytest-cov
          python -m pytest -v --cov=zarr --cov-config=pyproject.toml

      - name: Upload Pyodide wheel artifact for debugging
        # FIXME: Remove after this is ready to merge
        uses: actions/upload-artifact@v4
        with:
          name: zarr-pyodide-wheel
          path: dist/*.whl
