name: Slow Hypothesis CI
on:
  push:
    branches:
      - "main"
      - "v3"
  pull_request:
    branches:
      - "main"
      - "v3"
    types: [opened, reopened, synchronize, labeled]
  schedule:
    - cron: "0 0 * * *" # Daily “At 00:00” UTC
  workflow_dispatch: # allows you to trigger manually

env:
  FORCE_COLOR: 3

jobs:

  hypothesis:
    name: Slow Hypothesis Tests
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        python-version: ['3.11']
        numpy-version: ['1.26']
        dependency-set: ["optional"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install Hatch
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    - name: Set Up Hatch Env
      run: |
        hatch env create test.py${{ matrix.python-version }}-${{ matrix.numpy-version }}-${{ matrix.dependency-set }}
        hatch env run -e test.py${{ matrix.python-version }}-${{ matrix.numpy-version }}-${{ matrix.dependency-set }} list-env
    # https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache
    - name: Restore cached hypothesis directory
      id: restore-hypothesis-cache
      uses: actions/cache/restore@v4
      with:
        path: .hypothesis/
        key: cache-hypothesis-${{ runner.os }}-${{ github.run_id }}
        restore-keys: |
          cache-hypothesis-

    - name: Run slow Hypothesis tests
      if: success()
      id: status
      run: |
        hatch env run --env test.py${{ matrix.python-version }}-${{ matrix.numpy-version }}-${{ matrix.dependency-set }} run-hypothesis

    # explicitly save the cache so it gets updated, also do this even if it fails.
    - name: Save cached hypothesis directory
      id: save-hypothesis-cache
      if: always() && steps.status.outcome != 'skipped'
      uses: actions/cache/save@v4
      with:
        path: .hypothesis/
        key: cache-hypothesis-${{ runner.os }}-${{ github.run_id }}

    - name: Generate and publish the report
      if: |
        failure()
        && steps.status.outcome == 'failure'
        && github.event_name == 'schedule'
        && github.repository_owner == 'zarr-developers'
      uses: xarray-contrib/issue-from-pytest-log@v1
      with:
        log-path: output-${{ matrix.python-version }}-log.jsonl
        issue-title: "Nightly Hypothesis tests failed"
        issue-label: "topic-hypothesis"
