# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test V3

on:
  push:
    branches: [ v3 ]
  pull_request:
    branches: [ v3 ]

jobs:
  run-tests:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install Hatch
      run: |
        python -m pip install --upgrade pip 
        pip install hatch
    - name: Set Up Hatch Env
      run: |
        hatch env create
    - name: Run Tests
      run: |
        hatch run test:run
    - name: Run mypy
      continue-on-error: true
      run: |
        hatch run test:run-mypy