"""Render typed diagram specifications to deterministic SVG assets."""

from __future__ import annotations

import argparse
from pathlib import Path
from xml.etree.ElementTree import Element, SubElement, indent, tostring

if __package__:
    from .specifications import (
        FIGURES,
        PALETTES,
        ROLE_CUES,
        ArrowSpec,
        AxisSpec,
        ElementSpec,
        FigureSpec,
        GridSpec,
        NodeSpec,
        TextSpec,
        validate_figure,
    )
else:
    from specifications import (  # type: ignore[no-redef]
        FIGURES,
        PALETTES,
        ROLE_CUES,
        ArrowSpec,
        AxisSpec,
        ElementSpec,
        FigureSpec,
        GridSpec,
        NodeSpec,
        TextSpec,
        validate_figure,
    )


STYLESHEET_NAME = "indexing-guide.css"


def _stylesheet() -> str:
    lines = ["/* Generated by docs.diagrams.render; do not edit. */"]
    for scheme, palette in PALETTES.items():
        lines.append(f'[data-md-color-scheme="{scheme}"] {{')
        for role, colors in palette.items():
            for attribute, color in colors.items():
                lines.append(f"  --zi-{role}-{attribute}: {color};")
        lines.append("}")
    lines.extend(
        (
            ".zi-figure {",
            "  display: block;",
            "  width: 100%;",
            "  max-width: 100%;",
            "  height: auto;",
            "  font-family: system-ui, sans-serif;",
            "}",
            '.zi-figure[aria-labelledby~="chunk-overlay-title"] {',
            "  max-width: 528px;",
            "  margin-inline: auto;",
            "}",
            ".zi-figure text { dominant-baseline: middle; text-anchor: middle; font-size: 14px; }",
            ".zi-figure line, .zi-figure rect { vector-effect: non-scaling-stroke; }",
            ".zi-figure .zi-grid-cell { stroke-width: 1.5; }",
            ".zi-figure .zi-chunk-boundary { fill: none; stroke-width: 4; }",
            ".zi-figure .zi-arrow-line { fill: none; stroke-width: 2; }",
            ".zi-figure .zi-arrowhead { fill: var(--zi-text-stroke, #57606a); stroke: none; }",
            ".zi-figure .zi-role-label { font-size: 12px; font-weight: 650; text-anchor: start; }",
            ".zi-figure .zi-legend { pointer-events: none; }",
        )
    )
    for role, default_colors in PALETTES["default"].items():
        selector = f".zi-figure .zi-role-{role}"
        lines.extend(
            (
                f"{selector} {{",
                f"  fill: var(--zi-{role}-fill, {default_colors['fill']});",
                f"  stroke: var(--zi-{role}-stroke, {default_colors['stroke']});",
                f"  color: var(--zi-{role}-text, {default_colors['text']});",
                "}",
                f"{selector} text {{",
                f"  fill: var(--zi-{role}-text, {default_colors['text']});",
                "  stroke: none;",
                "}",
                f"{selector} line {{",
                f"  stroke: var(--zi-{role}-stroke, {default_colors['stroke']});",
                "}",
            )
        )
    lines.extend(
        (
            ".zi-figure .zi-role-request > rect, .zi-figure .zi-role-request .zi-cue-swatch { stroke-width: 3; }",
            ".zi-figure .zi-request-inner { fill: none; stroke-width: 1.5; }",
            ".zi-figure .zi-role-source > rect, .zi-figure .zi-role-source .zi-cue-swatch { stroke-width: 1.5; }",
            ".zi-figure .zi-role-source > rect.zi-chunk-boundary { stroke-width: 4; }",
            ".zi-figure .zi-role-source text.zi-unselected-coordinate-label { fill: var(--zi-source-stroke, #57606a); font-size: 11px; }",
            ".zi-figure .zi-role-selected, .zi-figure .zi-role-selected > rect { stroke-width: 4; }",
            ".zi-figure .zi-role-chunk-local > rect, .zi-figure .zi-role-chunk-local .zi-cue-swatch { stroke-width: 2; stroke-dasharray: 7 4; }",
            ".zi-figure .zi-role-cell-domain > rect, .zi-figure .zi-role-cell-domain .zi-cue-swatch { stroke-width: 2; }",
            ".zi-panel-row { display: flex; gap: 1rem; align-items: flex-start; }",
            (
                ".zi-figure-scroll { max-width: 100%; overflow-x: auto; "
                "overscroll-behavior-inline: contain; }"
            ),
        )
    )
    for spec in FIGURES:
        selector = (
            '.zi-figure-scroll .zi-figure[aria-labelledby~="'
            f'{spec["id"]}-title"]'
        )
        lines.append(f"{selector} {{ min-width: {min(spec['width'], 760)}px; }}")
    lines.extend(
        (
            "@media (max-width: 600px) {",
            "  .zi-panel-row { flex-wrap: wrap; overflow-x: visible; }",
            "  .zi-panel-row > * { flex: 1 1 100%; min-width: 0; }",
            "}",
        )
    )
    return "\n".join(lines) + "\n"


STYLESHEET = _stylesheet()


def _attributes(**attributes: object) -> dict[str, str]:
    return {name: str(value) for name, value in sorted(attributes.items())}


def _svg_element(parent: Element, tag: str, **attributes: object) -> Element:
    return SubElement(parent, tag, _attributes(**attributes))


def render_figure(spec: FigureSpec) -> str:
    """Render one validated figure as an accessible SVG string."""
    validate_figure(spec)
    root = Element(
        "svg",
        _attributes(
            **{
                "aria-labelledby": f"{spec['id']}-title {spec['id']}-desc",
                "class": "zi-figure",
                "role": "img",
                "viewBox": f"0 0 {spec['width']} {spec['height']}",
                "xmlns": "http://www.w3.org/2000/svg",
            }
        ),
    )
    _svg_element(root, "title", id=f"{spec['id']}-title").text = spec["title"]
    _svg_element(root, "desc", id=f"{spec['id']}-desc").text = spec["description"]
    definitions = _svg_element(root, "defs")
    marker = _svg_element(
        definitions,
        "marker",
        id=f"{spec['id']}-arrowhead",
        markerHeight=7,
        markerWidth=7,
        orient="auto-start-reverse",
        refX=6,
        refY=3.5,
        viewBox="0 0 7 7",
    )
    _svg_element(marker, "path", **{"class": "zi-arrowhead", "d": "M 0 0 L 7 3.5 L 0 7 z"})
    nodes = {
        element["id"]: element
        for element in spec["elements"]
        if element["kind"] == "node"
    }
    for element in spec["elements"]:
        _render_element(root, element, nodes, spec["id"])
    _render_legend(root, spec)
    indent(root)
    return tostring(root, encoding="unicode", short_empty_elements=True) + "\n"


def _render_element(
    parent: Element, element: ElementSpec, nodes: dict[str, NodeSpec], figure_id: str
) -> None:
    if element["kind"] == "grid":
        _render_grid(parent, element, figure_id)
    elif element["kind"] == "axis":
        _render_axis(parent, element, figure_id)
    elif element["kind"] == "node":
        _render_node(parent, element, figure_id)
    elif element["kind"] == "arrow":
        _render_arrow(parent, element, nodes, figure_id)
    elif element["kind"] == "text":
        _render_text(parent, element, figure_id)


def _group(parent: Element, element: ElementSpec, figure_id: str) -> Element:
    role = element["role"]
    return _svg_element(
        parent,
        "g",
        **{
            "aria-label": role,
            "class": f"zi-role-{role}",
            "data-non-color-cue": ROLE_CUES[role],
            "data-semantic-role": role,
            "id": f"{figure_id}-{element['id']}",
        },
    )


def _render_grid(parent: Element, element: GridSpec, figure_id: str) -> None:
    group = _group(parent, element, figure_id)
    origin_x, origin_y = element["origin"]
    for row in range(element["rows"]):
        for column in range(element["columns"]):
            classes = ["zi-grid-cell"]
            selected = (row, column) in element["selected"]
            cell_parent = group
            if selected:
                classes.append("zi-role-selected")
                cell_parent = _svg_element(
                    group,
                    "g",
                    **{
                        "aria-label": f"selected coordinate ({row}, {column})",
                        "class": "zi-role-selected zi-selected-cell",
                        "data-non-color-cue": ROLE_CUES["selected"],
                        "data-semantic-role": "selected",
                        "id": f"{figure_id}-{element['id']}-selected-{row}-{column}",
                    },
                )
            _svg_element(
                cell_parent,
                "rect",
                **{
                    "class": " ".join(classes),
                    "height": element["cell_size"],
                    "width": element["cell_size"],
                    "x": origin_x + column * element["cell_size"],
                    "y": origin_y + row * element["cell_size"],
                },
            )
            if selected:
                _svg_element(
                    cell_parent,
                    "text",
                    **{
                        "class": "zi-selected-coordinate-label",
                        "x": origin_x + (column + 0.5) * element["cell_size"],
                        "y": origin_y + (row + 0.5) * element["cell_size"],
                    },
                ).text = f"({row}, {column})"
            elif element.get("show_coordinates", False):
                _svg_element(
                    cell_parent,
                    "text",
                    **{
                        "aria-hidden": "true",
                        "class": "zi-unselected-coordinate-label",
                        "x": origin_x + (column + 0.5) * element["cell_size"],
                        "y": origin_y + (row + 0.5) * element["cell_size"],
                    },
                ).text = f"({row}, {column})"
    chunk_shape = element.get("chunk_shape")
    if chunk_shape is not None:
        chunk_rows, chunk_columns = chunk_shape
        for row in range(0, element["rows"], chunk_rows):
            rendered_rows = min(chunk_rows, element["rows"] - row)
            for column in range(0, element["columns"], chunk_columns):
                rendered_columns = min(chunk_columns, element["columns"] - column)
                _svg_element(
                    group,
                    "rect",
                    **{
                        "class": "zi-chunk-boundary",
                        "height": rendered_rows * element["cell_size"],
                        "width": rendered_columns * element["cell_size"],
                        "x": origin_x + column * element["cell_size"],
                        "y": origin_y + row * element["cell_size"],
                    },
                )


def _render_axis(parent: Element, element: AxisSpec, figure_id: str) -> None:
    group = _group(parent, element, figure_id)
    x1, y1 = element["x"], element["y"]
    if element["orientation"] == "horizontal":
        x2, y2 = x1 + element["length"], y1
    else:
        x2, y2 = x1, y1 + element["length"]
    _svg_element(group, "line", x1=x1, x2=x2, y1=y1, y2=y2)
    _render_label(group, x1, y1 - 14, str(element["start"]))
    _render_label(group, x2, y2 - 14, str(element["stop"]))


def _render_node(parent: Element, element: NodeSpec, figure_id: str) -> None:
    group = _group(parent, element, figure_id)
    rectangle = _svg_element(
        group,
        "rect",
        height=element["height"],
        width=element["width"],
        x=element["x"],
        y=element["y"],
    )
    if element["role"] == "cell-domain":
        rectangle.attrib.update(_attributes(rx=10, ry=10))
    if element["role"] == "request":
        _svg_element(
            group,
            "rect",
            **{
                "class": "zi-request-inner",
                "height": max(element["height"] - 8, 1),
                "width": max(element["width"] - 8, 1),
                "x": element["x"] + 4,
                "y": element["y"] + 4,
            },
        )
    _svg_element(
        group,
        "text",
        x=element["x"] + element["width"] / 2,
        y=element["y"] + element["height"] / 2,
    ).text = element["label"]


def _render_arrow(
    parent: Element, element: ArrowSpec, nodes: dict[str, NodeSpec], figure_id: str
) -> None:
    group = _group(parent, element, figure_id)
    source = nodes[element["source"]]
    target = nodes[element["target"]]
    source_x, source_y, target_x, target_y = _arrow_endpoints(source, target)
    _svg_element(
        group,
        "line",
        **{
            "class": "zi-arrow-line",
            "marker-end": f"url(#{figure_id}-arrowhead)",
            "x1": source_x,
            "x2": target_x,
            "y1": source_y,
            "y2": target_y,
        },
    )
    label_offset_x, label_offset_y = element.get("label_offset", (0, 0))
    _render_label(
        group,
        (source_x + target_x) / 2 + label_offset_x,
        (source_y + target_y) / 2 - 15 + label_offset_y,
        element["label"],
    )


def _node_center(node: NodeSpec) -> tuple[float, float]:
    return (node["x"] + node["width"] / 2, node["y"] + node["height"] / 2)


def _arrow_endpoints(source: NodeSpec, target: NodeSpec) -> tuple[float, float, float, float]:
    source_x, source_y = _node_center(source)
    target_x, target_y = _node_center(target)
    delta_x = target_x - source_x
    delta_y = target_y - source_y
    if delta_x == delta_y == 0:
        return source_x, source_y, target_x, target_y

    def edge_scale(node: NodeSpec) -> float:
        horizontal = node["width"] / (2 * abs(delta_x)) if delta_x else float("inf")
        vertical = node["height"] / (2 * abs(delta_y)) if delta_y else float("inf")
        return min(horizontal, vertical)

    source_scale = edge_scale(source)
    target_scale = edge_scale(target)
    return (
        source_x + delta_x * source_scale,
        source_y + delta_y * source_scale,
        target_x - delta_x * target_scale,
        target_y - delta_y * target_scale,
    )


def _render_text(parent: Element, element: TextSpec, figure_id: str) -> None:
    group = _group(parent, element, figure_id)
    _render_label(group, element["x"], element["y"], element["label"])


def _render_label(parent: Element, x: float, y: float, label: str) -> None:
    width = max(48, len(label) * 7 + 16)
    rectangle = _svg_element(
        parent,
        "rect",
        height=26,
        width=width,
        x=x - width / 2,
        y=y - 13,
    )
    if "zi-role-cell-domain" in parent.attrib.get("class", ""):
        rectangle.attrib.update(_attributes(rx=8, ry=8))
    _svg_element(parent, "text", x=x, y=y).text = label


def _render_legend(parent: Element, spec: FigureSpec) -> None:
    roles = tuple(
        dict.fromkeys(
            element["role"] for element in spec["elements"] if element["role"] != "text"
        )
    )
    if not roles:
        return
    legend = _svg_element(
        parent,
        "g",
        **{
            "aria-label": "Visible semantic role legend",
            "class": "zi-legend",
            "id": f"{spec['id']}-legend",
        },
    )
    columns = min(4, len(roles))
    column_width = min(170, (spec["width"] - 32) // max(columns, 1))
    rows = (len(roles) + columns - 1) // columns
    legend_bottom_padding = spec.get("legend_bottom_padding", 12)
    first_y = spec["height"] - legend_bottom_padding - 10 - (rows - 1) * 34
    for index, role in enumerate(roles):
        x = 22 + (index % columns) * column_width
        y = first_y + (index // columns) * 34
        item = _svg_element(
            legend,
            "g",
            **{
                "aria-label": role,
                "class": f"zi-role-{role}",
                "data-non-color-cue": _role_cue(role),
                "data-semantic-role": role,
                "id": f"{spec['id']}-legend-{role}",
            },
        )
        swatch = _svg_element(
            item,
            "rect",
            **{"class": "zi-cue-swatch", "height": 20, "width": 28, "x": x, "y": y - 10},
        )
        if role == "cell-domain":
            swatch.attrib.update(_attributes(rx=7, ry=7))
        if role == "request":
            _svg_element(
                item,
                "rect",
                **{
                    "class": "zi-request-inner",
                    "height": 14,
                    "width": 22,
                    "x": x + 3,
                    "y": y - 7,
                },
            )
        _svg_element(
            item,
            "text",
            **{
                "aria-label": role,
                "class": "zi-role-label",
                "data-non-color-cue": _role_cue(role),
                "data-semantic-role": role,
                "x": x + 36,
                "y": y,
            },
        ).text = role


def _role_cue(role: str) -> str:
    return next(cue for known_role, cue in ROLE_CUES.items() if known_role == role)


def render_all(output_dir: Path, *, check: bool) -> None:
    """Render all registered figures, or verify checked-in assets are current."""
    expected = {Path("diagrams") / f"{spec['id']}.svg": render_figure(spec) for spec in FIGURES}
    expected[Path(STYLESHEET_NAME)] = STYLESHEET
    if check:
        expected_bytes = {
            relative_path: contents.encode("utf-8") for relative_path, contents in expected.items()
        }
        actual: set[Path] = set()
        stylesheet = output_dir / STYLESHEET_NAME
        if stylesheet.exists():
            actual.add(Path(STYLESHEET_NAME))
        diagrams = output_dir / "diagrams"
        if diagrams.exists():
            actual.update(path.relative_to(output_dir) for path in diagrams.rglob("*.svg"))
        expected_paths = set(expected)
        for relative_path in sorted(expected_paths | actual):
            path = output_dir / relative_path
            if (
                relative_path not in expected_paths
                or not path.is_file()
                or path.read_bytes() != expected_bytes.get(relative_path)
            ):
                raise RuntimeError(f"stale generated diagram: {path}")
        return

    diagrams = output_dir / "diagrams"
    expected_paths = set(expected)
    if diagrams.exists():
        for path in diagrams.rglob("*.svg"):
            if path.relative_to(output_dir) not in expected_paths:
                path.unlink()
    for relative_path, contents in expected.items():
        path = output_dir / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents, encoding="utf-8", newline="\n")


def main() -> None:
    """Generate checked-in documentation assets, or verify them with ``--check``."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    render_all(Path(__file__).resolve().parents[1] / "_static", check=arguments.check)


if __name__ == "__main__":
    main()
