"""Render typed diagram specifications to deterministic SVG assets."""

from __future__ import annotations

from pathlib import Path
from xml.etree.ElementTree import Element, ElementTree, SubElement, indent, tostring

from .specifications import (
    FIGURES,
    ArrowSpec,
    AxisSpec,
    ElementSpec,
    FigureSpec,
    GridSpec,
    NodeSpec,
    TextSpec,
    validate_figure,
)


STYLESHEET_NAME = "zarr-indexing-diagrams.css"
STYLESHEET = """/* Generated by docs.diagrams.render; do not edit. */
.zi-figure { font-family: sans-serif; }
.zi-figure .zi-grid { fill: none; stroke: #64748b; }
.zi-figure .zi-request { fill: #dbeafe; stroke: #2563eb; }
.zi-figure .zi-source { fill: #dcfce7; stroke: #16a34a; }
.zi-figure .zi-selected { fill: #fef3c7; stroke: #d97706; }
.zi-figure .zi-chunk-local { fill: #f3e8ff; stroke: #9333ea; }
.zi-figure .zi-cell-domain { fill: #fee2e2; stroke: #dc2626; }
.zi-figure .zi-text { fill: #1f2937; stroke: #1f2937; }
.zi-figure .zi-chunk-boundary { fill: none; stroke-width: 2; }
"""


def _attributes(**attributes: object) -> dict[str, str]:
    return {name: str(value) for name, value in sorted(attributes.items())}


def _svg_element(parent: Element, tag: str, **attributes: object) -> Element:
    return SubElement(parent, tag, _attributes(**attributes))


def render_figure(spec: FigureSpec) -> str:
    """Render one validated figure as an accessible SVG string."""
    validate_figure(spec)
    root = Element(
        "svg",
        _attributes(
            **{
                "aria-labelledby": f"{spec['id']}-title {spec['id']}-desc",
                "class": "zi-figure",
                "role": "img",
                "viewBox": f"0 0 {spec['width']} {spec['height']}",
                "xmlns": "http://www.w3.org/2000/svg",
            }
        ),
    )
    _svg_element(root, "title", id=f"{spec['id']}-title").text = spec["title"]
    _svg_element(root, "desc", id=f"{spec['id']}-desc").text = spec["description"]
    nodes = {
        element["id"]: element
        for element in spec["elements"]
        if element["kind"] == "node"
    }
    for element in spec["elements"]:
        _render_element(root, element, nodes)
    indent(root)
    return tostring(root, encoding="unicode", short_empty_elements=True) + "\n"


def _render_element(parent: Element, element: ElementSpec, nodes: dict[str, NodeSpec]) -> None:
    kind = element["kind"]
    if kind == "grid":
        _render_grid(parent, element)
    elif kind == "axis":
        _render_axis(parent, element)
    elif kind == "node":
        _render_node(parent, element)
    elif kind == "arrow":
        _render_arrow(parent, element, nodes)
    elif kind == "text":
        _render_text(parent, element)


def _group(parent: Element, element: ElementSpec) -> Element:
    return _svg_element(parent, "g", **{"class": f"zi-{element['role']}", "id": element["id"]})


def _render_grid(parent: Element, element: GridSpec) -> None:
    group = _group(parent, element)
    origin_x, origin_y = element["origin"]
    for row in range(element["rows"]):
        for column in range(element["columns"]):
            classes = ["zi-grid-cell"]
            if (row, column) in element["selected"]:
                classes.append("zi-selected")
            _svg_element(
                group,
                "rect",
                **{
                    "class": " ".join(classes),
                    "height": element["cell_size"],
                    "width": element["cell_size"],
                    "x": origin_x + column * element["cell_size"],
                    "y": origin_y + row * element["cell_size"],
                },
            )
    chunk_shape = element.get("chunk_shape")
    if chunk_shape is not None:
        chunk_rows, chunk_columns = chunk_shape
        grid_width = element["columns"] * element["cell_size"]
        grid_height = element["rows"] * element["cell_size"]
        for column in range(chunk_columns, element["columns"], chunk_columns):
            x = origin_x + column * element["cell_size"]
            _svg_element(
                group,
                "line",
                **{
                    "class": "zi-chunk-boundary",
                    "x1": x,
                    "x2": x,
                    "y1": origin_y,
                    "y2": origin_y + grid_height,
                },
            )
        for row in range(chunk_rows, element["rows"], chunk_rows):
            y = origin_y + row * element["cell_size"]
            _svg_element(
                group,
                "line",
                **{
                    "class": "zi-chunk-boundary",
                    "x1": origin_x,
                    "x2": origin_x + grid_width,
                    "y1": y,
                    "y2": y,
                },
            )


def _render_axis(parent: Element, element: AxisSpec) -> None:
    group = _group(parent, element)
    x1, y1 = element["x"], element["y"]
    if element["orientation"] == "horizontal":
        x2, y2 = x1 + element["length"], y1
    else:
        x2, y2 = x1, y1 + element["length"]
    _svg_element(group, "line", x1=x1, x2=x2, y1=y1, y2=y2)
    _svg_element(group, "text", x=x1, y=y1).text = str(element["start"])
    _svg_element(group, "text", x=x2, y=y2).text = str(element["stop"])


def _render_node(parent: Element, element: NodeSpec) -> None:
    group = _group(parent, element)
    _svg_element(
        group,
        "rect",
        height=element["height"],
        width=element["width"],
        x=element["x"],
        y=element["y"],
    )
    _svg_element(
        group,
        "text",
        x=element["x"] + element["width"] / 2,
        y=element["y"] + element["height"] / 2,
    ).text = element["label"]


def _render_arrow(parent: Element, element: ArrowSpec, nodes: dict[str, NodeSpec]) -> None:
    group = _group(parent, element)
    source = nodes[element["source"]]
    target = nodes[element["target"]]
    source_x, source_y = _node_center(source)
    target_x, target_y = _node_center(target)
    _svg_element(group, "line", x1=source_x, x2=target_x, y1=source_y, y2=target_y)
    _svg_element(group, "text", x=(source_x + target_x) / 2, y=(source_y + target_y) / 2).text = (
        element["label"]
    )


def _node_center(node: NodeSpec) -> tuple[float, float]:
    return (node["x"] + node["width"] / 2, node["y"] + node["height"] / 2)


def _render_text(parent: Element, element: TextSpec) -> None:
    group = _group(parent, element)
    _svg_element(group, "text", x=element["x"], y=element["y"]).text = element["label"]


def render_all(output_dir: Path, *, check: bool) -> None:
    """Render all registered figures, or verify checked-in assets are current."""
    expected = {Path(f"{spec['id']}.svg"): render_figure(spec) for spec in FIGURES}
    expected[Path(STYLESHEET_NAME)] = STYLESHEET
    if check:
        expected_bytes = {relative_path: contents.encode("utf-8") for relative_path, contents in expected.items()}
        actual = {path.relative_to(output_dir) for path in output_dir.iterdir()} if output_dir.exists() else set()
        expected_paths = set(expected)
        for relative_path in sorted(expected_paths | actual):
            path = output_dir / relative_path
            if (
                relative_path not in expected_paths
                or not path.is_file()
                or path.read_bytes() != expected_bytes.get(relative_path)
            ):
                raise RuntimeError(f"stale generated diagram: {path}")
        return

    output_dir.mkdir(exist_ok=True)
    for relative_path, contents in expected.items():
        (output_dir / relative_path).write_text(contents, encoding="utf-8", newline="\n")
